name=Sheets Logger ESP
version=0.1.0
author=Cody <codysorgenfrey@gmail.com>
maintainer=Cody <codysorgenfrey@gmail.com>
sentence=An easy to use library for logging data to Google Sheets.
paragraph=This library provides a simple way to log data to Google Sheets from your ESP32 or ESP8266 device.
url=https://github.com/codysorgenfrey/esp_sheets_logger
architectures=esp32,esp8266
includes=SheetsLogger.h